services:
  web:
    image: leandromello99/simulador-do-caos:v2
    build:
      context: ./src
      dockerfile: Dockerfile
    ports: 
     - 8080:3000
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 2
    #   start_period: 30s